# config.py
LIMIT_CPU_M = 0
TIME_WINDOW_CPU = ""
LIMIT_NET_B = 0
TIME_WINDOW_NET = ""
COST_PER_CORE_HOUR = 0
DEFAULT_CPU_REQ = 0
DRY_RUN = True
WHITE_LIST_NS = []
TARGET_NAMESPACES = []
PROMETHEUS_URL = ""
DB_CONFIG = {}